### ISSUE TITLE
LV2 support

### ISSUE THREAD

**Issue by jofemodo** [qbroquetas/IV-XDelay#1]
Any chance of adding support for LV2?

**Comment by Vividinteract** [comment]
Hi,
I’m not sure what you’re referring to? I did look into the delay code and did like it very much. Presently I’m working on a multi-head echo myself although it’s a bit over my head due to my age I guess.

Please elaborate on your request.

Kind regards

Piet

**Comment by jofemodo** [comment]
LV2 is the "de-facto" standard plugin format on Linux systems. It's a very powerful and totally free plugin specification that is included in almost every modern linux distribution. Steinberg's VST is not an open plugin format and it's not well supported on Linux. By adding LV2 support, this plugin could be used by a greater number of users, in a greater number of systems, not only desktop computers. I mean Zynthian or MOD-Devices, that are specifically targeted for musicians.

Thanks

**Comment by Vividinteract** [comment]
Thanks for the explaining!!

I’ll read more on it.

As mentioned in my reply yesterday, I’m building a multi-head echo using Juce. I did design about 10 years ago that’s limited to 32-bit and written in a visual programming language. There is presently a need for a 64-bit solution by a small community. In-between I designed a DSP solution that’s also being used around the world. All as ‘labor for love’ with only material cost. The VST module, I’m presently, designing is just a brain-warming act as I’m 77. There is no outlook for completing as the task, although being trained in OOP its getting more difficult over time. The 32-bit took 350 manhours to design as most of the features of 6 complete different devices needed to be captures and emulated including 150 settings to play a large set of tracks known to have used that particular device and settings.

Kind regards,
Piet

P.s. www.vividinteract.com The Echotapper tab

**Comment by qbroquetas** [comment]
Hi there,

I'd very much like to write an LV2 version of this plugin. I designed the DSP algorithms independently from any JUCE libraries specifically for that purpose. However, the UI would have to be redesigned, and currently I don't have the time to do that. If anyone familiar with LV2 development would like to get involved, contact me and maybe we can work something out.

Pier, your project looks really interesting, I'll make sure to take a closer look at it when I can!

Joaquim.

**Comment by jofemodo** [comment]
Could you start by a GUI-less version. It's sub-optimal, but embbeded systems like zynthian & MOD-devices would take profit of a GUI-less version, allowing to integrate it and make it available on its collection.  Moreover, by having the GUI-less version, a lot of people having some of these devices could use the plugin and there is the possibility of some community member wanting to step forward and port the GUI.

**Comment by jofemodo** [comment]
Also, you could use a JUCE-LV2 wrapper, like DISTRHO:

https://github.com/DISTRHO/DISTRHO-Ports

@falkTX, the coder behind DISTRHO has sucesfully ported a lot of JUCE-based plugins using it.

**Comment by qbroquetas** [comment]
Actually, a GUI-less version sounds like a good starting point, as I also have an interest in embedded systems. At this moment I cannot allocate time to this project as I am committed to a research group working in the RF industry and with strict project deadlines. If this changes, revisiting this plugin would also have to include reworking the oversampling to achieve better computational efficiency, and that will most likely mean recalculating the FIR filters for different host sampling frequencies and oversampling ratios (and also resampling the noise tables). I also have measurements of the tape recorder I used with several other tapes, which I'd like to add to the plugin and provide the option to select between different tape formulations. 

I am glad that other people are taking an interest in this project, and thank you for your suggestions.
